### ISSUE TITLE
Extend the Readme

### ISSUE THREAD

**Issue by jekuno** [RowenStipe/qTox-OSX#1]
Nice project! I would be happy if you could add some details to the `Readme` regarding the following questions:
1. How is this project kept up to date with the most recent changes from the `qTox` repository? (do you do this manually or are the repos linked with each other?)
2. Do you build the `qTox-OSX.dmg` manually or does it happen fully automated on the server side?
3. Could you share the commands I need to run locally to build the `dmg` file myself from the contents in https://github.com/RowenStipe/qTox-OSX/tree/master/qtox.app/Contents? I would prefer this over executing an externally provided dmg file.

**Comment by RowenStipe** [comment]
I'll answer #3 here (partly) and say you could just use the Download ZIP button and it would do the same as the DMG file file I provide in both the repo and the release page. As for commands I used  `Disk Utility` in `~/Applications/Utilities` to make the file and added everything that in the repo except for the then created `dmg` package.

**Comment by jekuno** [comment]
Thanks for your fast answer. I understand that this final step only packages the files to an image.

Let me ask you how do you build the contents in https://github.com/RowenStipe/qTox-OSX/tree/master/qtox.app/Contents from the repository at  https://github.com/tux3/qTox. Is this something which happens automatically through a build script or do you do it manually? If you do it manually could you provide instructions how Mac OSX users can do this themselves?

**Comment by RowenStipe** [comment]
It's built manually because it's the only way I knew how to at the time to put the package out, I'm working on a instruction set listing how I build the qTox.app from https://github.com/tux3/qTox since I found the instruction set from their's to not work. I should be able to complete it with the newest qTox commit.

**Comment by jekuno** [comment]
That sounds promising.
IMHO it would be really nice if building a dmg file would happen automatically as soon as there's a new stable release of qTox. This would automatically keep the builds up to date (whether you're on holiday or not ;) )  and reduce error sources.

**Comment by RowenStipe** [comment]
Yes, that would be nice XD

For the moment releases aren't frequent enough that automation is 100% nessicarry but again it is being worked on when I can. 

Going to go ahead and close the issue since the latest release is now live and everything else should be straightened up now.

**Comment by jekuno** [comment]
All right. If I can assist or you need someone to test build on another OS X machine drop me a note.
