### ISSUE TITLE
You link against the wrong sodium version

### ISSUE THREAD

**Issue by stal888** [RowenStipe/qTox-OSX#2]
```
Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libsodium.13.dylib
  Referenced from: /Volumes/qTox/qTox.app/Contents/Frameworks/libtoxcore.0.dylib
  Reason: image not found
```

Frameworks has .17, should be a quick fix.

**Comment by RowenStipe** [comment]
So I've tracked this down to an issue with Toxcore when compiling the libs more specifically and obviously libtoxcore.0.dylib it calls for libsodium.13.dylib even though there was a recent libsodium update.

Why it does this I'm still looking into; I'd also like to apologize for the delay into looking into this. I'm doing what I can when I can with this.

**Comment by RowenStipe** [comment]
@_@; Okay after doing just a little more digging I realized I needed to update Toxcore's ./config with the updated locations to libsodium. That's done, updating the package and putting out the patch fix in a few.

Will close this if fixed on release.

**Comment by RowenStipe** [comment]
Okay! After having to fix a few other issues... I finally have a release I'd like for you to test to see if the same error persists.

https://github.com/RowenStipe/qTox-OSX/releases/download/PATCH-1.0.1.2/qTox-OSX-PATCH-1.0.1.2.dmg

**Comment by dangerrust** [comment]
It is too big

**Comment by subliun** [comment]
@dangerrust yes

but why

**Comment by stal888** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/774591/11435037/889da060-948a-11e5-8bdb-366406f11ed4.png)

**Comment by RowenStipe** [comment]
The `qtox.app` file in the dmg is what is provided when you pack all the required libraries to make it run on another persons machine with out installing them. With out this it's a 6.4 MB file that can only run on a system with all of the libraries present.

**Comment by stal888** [comment]
Can you get the download down to 30 MB or so?

**Comment by RowenStipe** [comment]
I honestly don't know, as far as I can tell with qTox's current code build and the additional step of adding in the libraries which are not standard across OS X for use the current `qTox.app` file size stands at `52.1 MB`

**Comment by stal888** [comment]
I think it's just a matter of telling hdiutil to use compression.

**Comment by RowenStipe** [comment]
Compressing it does bring the .dmg file down to `25 MB` Still pretty damn big compared to many other Tox builds I'll admit.

Edit: Updated release link to compressed version: https://github.com/RowenStipe/qTox-OSX/releases/tag/PATCH-1.0.1.2

**Comment by stal888** [comment]
works for me

you can go ahead and add a link to the main binaries page on the wiki.

if another cabal member complains point them to me

**Comment by RowenStipe** [comment]
Would but my wiki account doesn't have the perms to edit the binaries page, would need to be something done by a higher perm account.
