### ISSUE TITLE
webcam issue

### ISSUE THREAD

**Issue by tristan-k** [RowenStipe/qTox-OSX#4]
According to https://github.com/tux3/qTox/issues/2129#issuecomment-162264343 commit https://github.com/tux3/qTox/commit/94a6df47ccdeb7dd331be1478dbbf0bf1087dab0 seems to patch the webcam issue. Can you compile and confirm?

**Comment by RowenStipe** [comment]
I wish this was the case but the webcam functionality is still not working due to `avfoundation` not being set up and as of this moment it's something that's beyond my own ability with coding to attempt patching a fix.

**Comment by TheNain38** [comment]
Should be fixed by tux3/qTox#2714

**Comment by RowenStipe** [comment]
This issue is now resolved with the latest release: https://github.com/RowenStipe/qTox-OSX/releases/tag/1.2.2.184

**Comment by tristan-k** [comment]
Thanks. Works flawlessly.
